### ISSUE TITLE
[Bug]: AreaChart - Error when all scores are null

### ISSUE THREAD

**Issue by LaurentDario** [gsoft-inc/ov-igloo-ui#580]
### Contact Details

laurent.jouanneau@gsoft.com

### What happened?

When the data set used in the AreaChart has only `null` scores, the graph errors out instead of displaying an empty graph. This is problematic in our usage of the component.
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/234418/360b22a6-667e-4a85-8bb5-210400825e05)

### Component

AreaChart

### Component Version

1.0.1

### Which browsers are you seeing the problem on?

Chrome

### Relevant log output

```
Error: Cannot read properties of undefined (reading 'score')
  at Array.map (<anonymous>))
  at getFakeScore (/storybook/AreaChart-stories.b3ee9eb1.iframe.bundle.js:1:20553))
  at /storybook/AreaChart-stories.b3ee9eb1.iframe.bundle.js:1:21590
  at qi (/storybook/8237.baeda6e6.iframe.bundle.js:532:446894))
  at Yi (/storybook/8237.baeda6e6.iframe.bundle.js:532:458688))
  at bj (/storybook/8237.baeda6e6.iframe.bundle.js:532:459325))
  at aj (/storybook/8237.baeda6e6.iframe.bundle.js:532:459209))
  at bj (/storybook/8237.baeda6e6.iframe.bundle.js:532:459305))
  at aj (/storybook/8237.baeda6e6.iframe.bundle.js:532:459209))
```

**Comment by vicky-comeau** [comment]
I have just merged a fix for this as a patch.
